encoding: utf-8
port: 5678
host: 0.0.0.0
#incremental: true
#timezone: CN
title: Fooleap's Blog
email: fooleap@gmail.com
keywords: [fooleap, 前端, Linux, 潮汕]
description: 'A foolish man could not always lose!'
home: http://blog.fooleap.org
api: http://api.fooleap.org
IMG_PATH: http://source.fooleap.org
tongji: 'fa7ec982118ebd236663169678264582'
analytics: 'UA-16717905-7'
highlighter: rouge
permalink: /:title.html
paginate: 10
markdown: kramdown
exclude: ['media', 'update.lftp', 'pushbaidu.sh', '.htaccess']
repository: fooleap/fooleap.github.io
twitter_username: fooleap
weibo_username: fooleap
sass:
    sass_dir: _sass
    style: :compressed
kramdown: 
    auto_ids:       true
    auto_id_prefix: 'id-'
    toc_levels:     '2,3'
    smart_quotes:   lsquo,rsquo,ldquo,rdquo
gems: 
      - jekyll-paginate
      - jekyll-coffeescript
      - jekyll-github-metadata
      - jemoji
