encoding: utf-8
port: 5678
host: 0.0.0.0

title: Fooleap's Blog
keywords: [fooleap, 前端, Linux, 潮汕]
description: 'A foolish man could not always lose!'

permalink: /:title.html
exclude: ['media', 'update.lftp', 'pushbaidu.sh', '.htaccess']
sass:
    sass_dir: _sass
    style: :compressed
highlighter: rouge
markdown: kramdown
kramdown: 
    auto_ids:       true
    auto_id_prefix: 'id-'
    toc_levels:     '2,3'
    smart_quotes:   lsquo,rsquo,ldquo,rdquo
gems: 
      - jekyll-paginate
      - jekyll-coffeescript
      - jemoji
paginate: 10
repository: fooleap/fooleap.github.io

nickname: fooleap
home: http://blog.fooleap.org
api: http://api.fooleap.org
IMG_PATH: http://source.fooleap.org
tongji: 'fa7ec982118ebd236663169678264582'
analytics: 'UA-16717905-7'
