encoding: utf-8
title: Fooleap's Blog
email: fooleap@gmail.com
keywords: [fooleap, 前端, Linux, 潮汕]
description: 'A foolish man could not always lose!'
url: 'http://blog.fooleap.org'
timezone: CN
permalink: /:title.html 
highlighter: rouge
gems: [jekyll-paginate]
paginate: 10
IMG_PATH: http://source.fooleap.org
markdown: kramdown
exclude: ['media', 'update.lftp', 'pushbaidu.sh', '.htaccess']
sass:
  sass_dir: _sass
  style: :compressed
kramdown: 
  auto_ids:       true
  auto_id_prefix: 'id-'
  toc_levels:     '2,3'
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
defaults:
  -
    scope:
      path: '_posts'
      type: posts 
    values:
      is_post: true
twitter_username: fooleap
github_username: fooleap
weibo_username: fooleap
