encoding: utf-8
title: Fooleap's Blog
email: fooleap@gmail.com
description: "A foolish man could not always lose!"
url: "http://blog.fooleap.org"
twitter_username: fooleap
github_username: fooleap
weibo_username: fooleap
timezone: Asia/Shanghai
permalink: /:title.html 
highlighter: pygments
paginate: 10
IMG_PATH: http://7fv9cr.com1.z0.glb.clouddn.com
markdown: kramdown
kramdown: 
  toc_levels: "2" 
